- name: variables from files
  hosts: node2 #if localhost we can managing the ansible server itself
  vars_files:
  - variables.yaml
  tasks:
  - name: Printing variables
    ansible.builtin.debug:
      msg: "We are learning {{NAME}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"