- name: variables at task level
  hosts: node2
  # thses variables of parent or play level
  vars:
  - money: "100000 RS"
    land: "10 acres"
  tasks:
  - name: Inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: Inherit values from play and add and override
    vars:
    - money: "200000 RD"
      houses: "3 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"