- name: Install packeges
  hosts: node2
  become: yes
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: present
    # list of string
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx